### ISSUE TITLE
do you consider add security and send messages to special user 

### ISSUE THREAD

**Issue by keryhu** [martamedio/SecurityWebsocketAngular2#1]
Hi, this is a good example ..

recently ,i try to use websocket and angular2 , spring can send messages publish/subscribe,

but met problems with sending messages to special user.

Don't know if you will consider adding this feature？ or give some suggestion

**Comment by martamedio** [comment]
What do you mean with "sending messages to special user"? 
Do you want to send a message to an specific user, and only that user, through the websocket? To do that all connections will need a unique ID associated to each user and you should filter your logic of return by that ID+User.

**Comment by keryhu** [comment]
@martamedio 
yes, I mean :  send a message to an specific user, and only that user, through the websocket

 all connections will need a unique ID associated to each user and you should filter your logic of return by that ID+User.?

you mean: client set"new SockJS(**endpointUrl**)", the **endpointUrl** add unique ID  
or  

> messagingTemplate
>         .convertAndSendToUser(principal.getName(), "/queue/horray", "Horray, " + principal.getName() + "!");

**Comment by martamedio** [comment]
In Spring you can use the _@SendToUser_ annotation, you can check how to do [it at the reference](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-user-destination)

When subscribing in Angular (or any other library) you would need to make sure the client subscribes to the correct URL, something like: 
`let ws = new $WebSocket("ws://localhost:9090/message"+uniqueID);`

Whit this you I think that you could solve it.

**Comment by keryhu** [comment]
First , thanks your answer .
refer to spring document , uniqueID is sessionId? or principal name?  but angular2 with spring is a stateless security ,  I do not know how to get the `uniqueID`

How spring boot create **uniqueID** of the socket endpoint url `message"+uniqueID`?

**Comment by martamedio** [comment]
It's the principal name, if you check the examples of _@SendToUser_ you will see that it's the field for filter; at the webclient you'll need to have the username that it's logged in.
You have a lot of examples (for example, [this one](http://assets.spring.io/wp/WebSocketBlogPost.html)) about how to do it at Spring and the URL to subscribe at the Front-End, it's not related to the language (Angular2 in this case) that you are using.
